### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ralvescosta**

### CODE REVIEW

**Review by DPechetti — APPROVED** [review]

**Review by DPechetti — COMMENTED** [review]
we have badges for this?

put the badges too hehe

**Comment by ralvescosta** [comment]
@bruno8moura please accept the PR

**Comment by ralvescosta** [comment]
@DPechetti @bruno8moura 

```bash
npx oloquinho
```

**Comment by bruno8moura** [comment]
> @bruno8moura please accept the PR

Done!

**Pull request merged**
